const songList = [
  {
    songTitle: "Party No dey Stop (remix)",
artist: "Adekunle Gold",
sourceFile: "party-no-dey-stop-jayo-byron-messia-remix-1__1698435925.m4a",
index: 0, 
},
  {
    songTitle: "Alimi",
artist: "Portable",
sourceFile: "music/alimi__1695839924.m4a",
index: 0, 
},
  {
    songTitle: "Ask About Me",
artist: "Mohbad",
sourceFile: "music/ask-about-me-__1687534876.m4a",
index: 0, 
},
  {
    songTitle: "Coming_for_You",
artist: "SwitchOTR",
sourceFile: "music/SwitchOTR_-_Coming_for_You.mp3",
index: 0, 
},

  {
    songTitle: "Ed Sheeran Castle On The Hill",
artist: "Ed Sheeran",
sourceFile: "music/Ed_Sheeran_-_Castle_On_The_Hill_ObaMedia.Com.Ng.mp3",
    next: 1,
},
{songTitle: "walking dead(late Mohbad 😥)",
artist: "Mohbad",
sourceFile: "music/Mohbad-Walking-Dead-(JustNaija.com).mp3",
 next: 2,
},
{
songTitle: "Feel-Good(late Mohbad 😥)",
artist: "Mohbad",
sourceFile: "music/Mohbad-Feel-Good-(TrendyBeatz.com).mp3",
  next: 3,
},
  {
songTitle: "La pio pio(late Mohbad 😥)",
artist: "Mohbad",
sourceFile: "music/Mohbad-La-Pio-Pio-(JustNaija.com).mp3",
next: 4,
  },
  {
songTitle: "Sabi(late Mohbad 😥)",
artist: "Mohbad",
sourceFile: "music/Mohbad-Sabi-(JustNaija.com).mp3",
    next: 5,
},
  {
songTitle: "Father Abraham(late Mohbad 😥)",
artist: "Mohbad",
sourceFile: "music/Mohbad-Father-Abraham-(JustNaija.com).mp3",
    next: 6,
},
  {
songTitle: "Ronaldo(late Mohbad 😥)",
artist: "Mohbad",
sourceFile: "music/Mohbad_-_Ronaldo.mp3",
    next: 7,
},
{
  songTitle: "Comment Ne Pas",
  artist: "Philip Beli",
  sourceFile: "music/Bebi_Philip_-_Comment_Ne_Pas_Te_Louer_CeeNaija.com_.mp3",
  next: 8,
 },
{
  songTitle: "Jama",
  artist: "Dj Mic Smith ft Patoranking",
  sourceFile: "music/jama.mp3",
  next: 9,
 },
 {
  songTitle: "Magbe(Qdot)",
  artist: "Qdot ft Patoranking",
  sourceFile: "music/magbe(Qdot).mp3",
   next: 10,
 },
 {
  songTitle: "Everytime we touch",
  artist: "unknown",
  sourceFile: "music/Every_time_we_touch.mp3",
   next: 11,
 },
 {
  songTitle: "Finesse",
  artist: "Pheelz ft Buju",
  sourceFile: "music/Pheelz-Ft-Buju-Finesse-(TrendyBeatz.com).mp3",
   next: 12,
 },
 {
  songTitle: "At My Worst",
  artist: "Unknown",
  sourceFile: "music/atmyworst.mp3",
   next: 14,
 },
 {
  songTitle: "Anabella",
  artist: "Khaid",
  sourceFile: "music/Anabella.mp3",
   next: 15,
 },
 {
  songTitle: "Door",
  artist: "Joeboy",
  sourceFile: "music/Door.mp3",
   next: 16,
 },
  {
  songTitle: "Feel(Davido)",
  artist: "Davido",
  sourceFile: "music/davido-feel.mp3",
    next: 17,
 },
 {
  songTitle: "lonely at the top | ASAKE",
  artist: "Asake",
  sourceFile: "music/lonely at the top.mp3",
   next: 18,
 },
 {
  songTitle: "Cough(Remix)",
  artist: "Kizz Daniel ft Becky G",
  sourceFile: "music/cough(remix).mp3",
   next: 19,
 },
  {
  songTitle: "Come and Go",
  artist: "Ardee",
  sourceFile: "music/come and go.mp3",
    next: 20,
 },
 {
  songTitle: "Sability",
  artist: "Ayrra Starr",
  sourceFile: "music/sability.mp3",
   next: 21,
 },
  {
  songTitle: "Alcohol",
  artist: "Joeboy",
  sourceFile: "music/Alcohol-joeboy.mp3",
next: 22,
 },
  {
  songTitle: "Confession-AV",
  artist: "AV",
  sourceFile: "music/Confession-AV.mp3",
    next: 24,
 },
 {
  songTitle: "Celebrate Me",
  artist: "Patoranking",
  sourceFile: "music/celebrate me.mp3",
   next: 25,
 },
  {
  songTitle: "Calm Down",
  artist: "Rema",
  sourceFile: "music/Calm_Down.mp3",
    next: 26,
 },
]

export {songList}
